#ifndef _PLATFORM_CONFIG_H_
#define _PLATFORM_CONFIG_H_

#define PLATFORM_ARDUINO_NANO

#define PIN_INPUT INPUT
#define PIN_OUTPUT OUTPUT
#define PIN_HIGH HIGH
#define PIN_LOW LOW
#define UART_BUFFER_SIZE 10
#define UART_PRINTF_BUFFER_SIZE 80

#define SPI_SS_PIN 10
#define SPI_MOSI_PIN 11
#define SPI_MISO_PIN 12
#define SPI_SCK_PIN 13

#define DISPLAY_I2C
#define DISPLAY_I2C_ADDR 0x26

#define NRF24_CSN_PIN 8
#define NRF24_CE_PIN 7

// #define DISPLAY_NORITAKE
// #define NORITAKE_SIO 4
// #define NORITAKE_STB 5
// #define NORITAKE_SCK 6

#endif // _PLATFORM_CONFIG_H_
