#ifndef _PLATFORM_CONFIG_H_
#define _PLATFORM_CONFIG_H_

#define PLATFORM_ARDUINO_NANO

#define PIN_INPUT INPUT
#define PIN_OUTPUT OUTPUT
#define PIN_HIGH HIGH
#define PIN_LOW LOW
#define UART_BUFFER_SIZE 80

#define DISPLAY_BUFFER_SIZE 80
#define DISPLAY_NORITAKE
#define NORITAKE_SIO 10
#define NORITAKE_STB 11
#define NORITAKE_SCK 12

#endif // _PLATFORM_CONFIG_H_
